apiVersion: v1
kind: Namespace
metadata:
  name: crocodille-erp

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: crocodille-erp
  name: crocodille-erp
  namespace: crocodille-erp
spec:
  selector:
    app: crocodille-erp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crocodille-erp
  namespace: crocodille-erp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /crocodille-erp(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: crocodille-erp
                port:
                  number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crocodille-erp
  namespace: crocodille-erp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: crocodille-erp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crocodille-erp
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - image: ghcr.io/radixal-sro/crocodille-erp:latest
          imagePullPolicy: Always
          name: crocodille-erp
          ports:
            - containerPort: 80
              protocol: TCP
